### ISSUE TITLE
Npm install -g

### ISSUE THREAD

**Issue by raix** [zeroasterisk/sonos-simple-cli#1]
Nice project @zeroasterisk - sonos is great

Hints for `npm install sonos-simple-cli -g`:

Add this to the top of `sonos.js`

``` js
#!/usr/bin/env node
```

Modify the package.json:

``` js
  // Replace main with:
  "preferGlobal": "true",
  "bin": {
    "sonos-simple-cli": "sonos.js"
  }
```

Then npm publish? :)

Kind regards Morten

**Comment by zeroasterisk** [comment]
hey - thanks!

do you happen to have Sonos speakers?  if so, play with this and let me know what you think -- it's solved a problem I've been complaining about for a long time, no global shortcut keys.

**Comment by raix** [comment]
Actually got my first yesterday, thinking about buying 10 more and have it set up around the house... The kids are already using it - with no guidance... what geeks! :)

Just have to find some good streaming / radio services,

I've installed it successfully - I tried `sonos-simple-cli mute` but it hangs after a few sec, any debugging tips?

**Comment by zeroasterisk** [comment]
update to latest, should now work.

you'll have to configure for "which" room name you want, crappy prompt for it if not configured now.

Hangouts me if you wanna debug... 

_The controller not having keyboard shortcuts is a pain, which is why I made this._
